version: 2.1
orbs:
  node: circleci/node@4.5.1
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: git clone --recursive https://github.com/PaulieScanlon/gsap-bonus
      - run: git submodule sync
      - run: git submodule update --init
      - run: yarn install
      - run: yarn test -u

workflows:
  build-and-test:
    jobs:
      - build-and-test
